version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "passWord"

phases:
  install:
    commands:
      - echo pre_build on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `cat /etc/system-release`
      - echo `pwd`
      - echo `cat /etc/passwd`
      - echo `adduser batchuser`
      - echo `cat /etc/passwd`
      - echo `su - batchuser; whoami`
      - echo `pwd`
      - echo `ls -l`
　　　　　- echo `sh sutest.sh`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

