version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "passWord"

phases:
  install:
    commands:
      - echo pre_build on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `cat /etc/system-release`
      - echo `pwd`
      - echo `cat /etc/passwd`
      - echo `sh ./sutest.sh`
      - echo `ls -l`
      - echo `cat /etc/passwd`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

