version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "aaaa"

phases:
  install:
    commands:
      - echo pre_build on `date`
      - echo `useradd testtest -p batchuser_pass`
      - echo `cat /etc/passwd`
      - echo `cp README.md /home/testtest/.`
      - echo `runuser -l testtest -c "touch text.txt"`
      - echo `runuser -l testtest -c "ls -l"`
      - echo `ls -l`
      - echo `printenv env1`
      - echo `aws s3 ls`
      - echo `aws s3 cp s3://ir-etl-dev-tokyo/logs/693162eb27b8_1484312613635_00000f94_noticeErr.txt .`
      - echo `mv 693162eb27b8_1484312613635_00000f94_noticeErr.txt /home/testtest/.`
      - echo `chown testtest:testtest /home/testtest/693162eb27b8_1484312613635_00000f94_noticeErr.txt`
      - echo `runuser -l testtest -c "ls -l"`
      - echo `ls -l`

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`

  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

