version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "aaaa"

phases:
  install:
    commands:
      - echo pre_build on `date`
      - echo `useradd testtest -p batchuser_pass`
      - echo `cat /etc/passwd`
      - echo `sudo su - testtest; whoami`

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`

  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

