version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "passWord"

phases:
  install:
    commands:
      - echo pre_build on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `cat /etc/system-release`
      - echo `pwd`
      - echo `cat /etc/passwd`
      - echo `adduser batchuser -p password`
      - echo `cat /etc/passwd`
      - echo `"password" | su - batchuser; whoami`
      - echo `pwd`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

